# Generated by Django 5.2.5 on 2025-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeedetails_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
