# Generated by Django 5.2.5 on 2025-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeedetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
